<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify Chino</title>
</head>

<body>
    <form action="" method="POST" enctype="multipart/form-data">
        <label>Título</label>
        <input type="text" name="song-title" id="">
        <label>Autor</label>
        <input type="text" name="song-author" id="">
        <label>Minutos</label>
        <input type="number" name="song-mins" id="">
        <label>Segundo</label>
        <input type="number" name="song-secs" id="">
        <input type="file" name="song-mp3" id="">
        <input type="submit" value="Crear Cancion">
    </form>
    <?php
    echo '<form action="index.php" method="GET">
        <label>Buscar</label>
        <input list="song" type="text" name="song-search" id="">
        <datalist id="song">';
    foreach ($songs as $song) {
        echo '<option value="' . $song->getTitle() . '">' . $song->getAuthor() . '</option>';
    }
    echo '</datalist>
    <input type="hidden" name="c" value="cancion" id="">
        <input type="hidden" name="pl-id" value=' . $_GET['pl-id'] . ' id="">
        <input type="submit" value="Buscar">
    </form>';
    if (!empty($songsSearched)) {
        foreach ($songsSearched as $song) {
            echo 'Título: ' . $song->getTitle() . '<br>';
            echo 'Autor: ' . $song->getAuthor() . '<br>';
            echo 'Duracion: ' . $song->getDurationFormatted() . '<br>';
            echo '<a href="index.php?c=cancion&pl-id=' . $_GET['pl-id'] . '&song-search=' . $_GET['song-search'] . '&add-song=' . $song->getId() . '">Añadir Canción</a><br>';
        }
    }
    ?>
</body>

</html>