<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify Chino</title>
</head>

<body>
    <form action="index.php?c=listaReproduccion&pl=1" enctype="multipart/form-data" method="post">
        <input type="text" name="pl-name" id="">
        <input type="file" name="pl-img" id="">
        <input type="submit" value="Crear Playlist">
    </form>
</body>

</html>