<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify Chino</title>
</head>

<body>
    <?php
    echo '<form enctype="multipart/form-data" action="index.php?c=cancion&adm-song=1&index=1" method="POST">
        <label>Titulo</label>
        <input type="text" placeholder="' . $song->getTitle() . '" name="song-title-edit"/>
        <label>Autor</label>
        <input type="text" placeholder="' . $song->getAuthor() . '" name="song-author-edit" id=""/>
        <input type="file" name="song-mp3-edit" id="">
        <input type="hidden" name="song-id" value="' . $song->getId() . '"/>
        <input type="submit" value="Editar Canción">
    </form>';
    ?>
</body>

</html>