<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify Chino</title>
</head>

<body>

    <?php
    echo '<form action="index.php" method="GET">
    <label>Buscar</label>
    <input list="playlist" type="text" name="search" id="">
    <datalist id="playlist">';
    foreach ($playlists as $playlist) {
        echo '<option value="' . $playlist->getName() . '">' . $playlist->getCreator()->getName() . '</option>';
    }
    echo '</datalist>
    <input type="hidden" name="c" value="listaReproduccion" id="">
    <input type="hidden" name="search-pl" value="1" id="">
    <input type="submit" value="Buscar">
    </form>';
    if (!empty($searchedPlaylists)) {
        foreach ($searchedPlaylists as $playlist) {
            echo '<a href="index.php?c=listaReproduccion&show-pl=' . $playlist->getId() . '"><h2>' . $playlist->getName() . ' - ' . count($playlist->getSongs()) . ' canciones</h2></a>';
            if ($_SESSION['user']->getName() == $playlist->getCreator()->getName()) {
                echo '<a href="index.php?c=cancion&pl-id=' . $playlist->getId() . '">Añadir Cancion</a><br>';
            }
            if ($_SESSION['user']->isFavourite($playlist->getId())) {
                echo '<a href="index.php?c=listaReproduccion&show-pl=' . $playlist->getId() . '&fav=0">Quitar de favoritos</a>';
            } else {
                echo '<a href="index.php?c=listaReproduccion&show-pl=' . $playlist->getId() . '&fav=1">Añadir a favoritos</a>';
            }

            foreach ($playlist->getSongs() as $song) {
                echo '<p>' . $song->getTitle() . ' - ' . $song->getAuthor() . '</p>';
            }
            echo '<p>Creador: <strong>' . $playlist->getCreator()->getName() . '</strong></p>';
        }
    }
    ?>


</body>

</html>